gcloud beta compute instances create-with-container redis \
  --machine-type n1-standard-1 \
  --boot-disk-size "15" \
  --boot-disk-type "pd-standard" \
  --container-image redis:4.0.9 \
  --container-mount-host-path mount-path=/data,host-path=/mnt/stateful_partition/data,mode=rw \
  --container-command "redis-server" \
  --container-arg "--databases 1" \
  --container-arg "--save 3600 1" \
  --container-arg "--save 1800 100" \
  --container-arg "--save 600 10000" \
  --container-arg "--maxmemory 3gb" \
  --container-arg "--maxmemory-policy allkeys-lru"
